### ISSUE TITLE
What do the 12 bytes at the end of the file mean?

### ISSUE THREAD

**Issue by fcrisafulli-dev** [SoslanGM/HxApy_Blender_import-export#1]
Hello, I am trying to create a HxA parser in Rust using files exported from this plugin.

I have noticed after parsing though the data of the Blender default cube, that there are 12 bytes left.

I am assuming there are 3 u32s here
``` 00 00 00 00 06 00 00 00 00 00 00 00 00```

This follows immediately after a "reference" HXALayer (which is the last layer in the file in my case)

The default cube uses quads, which leads me to believe that the number indicates the face count.
After triangulating the cube, the number doubled to 12 which may confirm my assumption.

I don't see anything about these bytes in the original specification for HxA, so I was wondering if this was an unfinished Face HXALayer

I have provided the file I am using here:
[cube_hxa.zip](https://github.com/SoslanGM/HxApy_Blender_import-export/files/10942848/cube_hxa.zip)

**Comment by fcrisafulli-dev** [comment]
After looking though the source of this repo, it seems that the last 12 bytes are indeed an empty HXALayer and the number of faces in the mesh, followed by another empty HXALayer.

**Comment by SoslanGM** [comment]
Hey @fcrisafulli-dev, sorry for leaving you hanging. This was a wrong day to not check my email(missed another thing and had to dash for it :'D)
